splash = false

wallpaper {
    monitor = DP-3
    path = /home/tayron/Bilder/Wallpapers/wallpaper.jpeg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/tayron/Bilder/Wallpapers/wallpaper.jpeg
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = /home/tayron/Bilder/Wallpapers/wallpaper.jpeg
    fit_mode = cover
}
